-- Migration 003: Add LLM classification fields to predictions table
-- This is additive only; does not remove or modify existing columns.
--
-- NOTE: This file is documentation only. The executable migrations live in
-- mailmind/storage/migrations.py, where the prediction columns are added with
-- per-column existence checks. See migration 0010 for the LLM metadata fields.

-- The following columns are added programmatically via Python:
-- llm_label          TEXT      — LLM-classified label
-- llm_confidence     REAL     — LLM confidence score (0.0–1.0)
-- llm_rationale      TEXT     — One-sentence rationale from LLM
-- llm_action_hint    TEXT     — Suggested action from LLM (nullable)
-- llm_needs_review   INTEGER  — 1 if human review is needed, else 0
-- classifier_source  TEXT     — "rules" | "ml" | "llm" | "fallback"
-- llm_called_at      TEXT     — ISO-8601 timestamp when LLM was called
